import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { readFile } from "node:fs/promises";

// Obsidian plugins may only ship main.js, manifest.json and styles.css,
// so drop the file-based @font-face rules from the bpmn icon font and
// keep only the base64-embedded copy, which styles.css carries itself.
const embeddedFontOnly = {
    name: "embedded-font-only",
    setup(build) {
        build.onLoad({ filter: /bpmn-font\/css\/bpmn-embedded\.css$/ }, async (args) => {
            let css = await readFile(args.path, "utf8");
            css = css.replace(/@font-face\s*\{[^}]*#iefix[^}]*\}/g, "");
            return { contents: css, loader: "css" };
        });
    },
};

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts', 'src/styles.css'],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: '.',
    plugins: [embeddedFontOnly]
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
