// eslint.config.mjs
import { defineConfig } from "eslint/config";
import obsidianmd from "eslint-plugin-obsidianmd";

export default defineConfig([
  {
    // main.js is the built bundle (regenerated by esbuild)
    ignores: ["main.js"],
  },
  ...obsidianmd.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["eslint.config.*", "esbuild.config.*"],
        },
      },
    },
    rules: {
      "obsidianmd/ui/sentence-case": "off",
      "obsidianmd/no-nodejs-modules": "off",
      // The plugin is named "bpmn", so this rule flags every command that
      // contains the word "BPMN" — the domain term, not the plugin prefix.
      "obsidianmd/commands/no-plugin-name-in-command-name": "off"
    }
  },
]);
